# Generated by Django 3.0.7 on 2020-07-02 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=196)),
                ('age', models.TextField(default='Age 18-24')),
                ('health', models.TextField(default='Asthma')),
                ('message', models.TextField()),
            ],
        ),
    ]
